### ISSUE TITLE
Don't see any indication of .NET Core 2 Standard support

### ISSUE THREAD

**Issue by hubert-associates** [Chinchilla-Software-Com/CQRS#127]
Just wondering what the take is here on usage in a .NET Core 2 environment. Thanks.

**Comment by cdmdotnet** [comment]
Given the main usage of the library with our clients is current on IIS, .NET Core currently lacks several features in the full .NET framework which simplifies much of the complexities associated with highly scaleable systems.

We're watching developments on .NET Core and just awaiting the missing features required.

I'm sure the last thing you'd want is a cut down library that requires you basically building/coding fundamental ports yourself rather having having a complete platform... that's what we're currently focusing on... a complete platform.

**Comment by hubert-associates** [comment]
Thanks for the clarification. Your reasoning is very understandable. We are in a different lot :-) We are starting to develop new SaaS (On-Demand/Azure) systems which must also be deployable on-premises. Clearly, we would not want to bootstrap a new generation of software on the "old" stack, even if IIS is still quite prevalent in the On-Prem landscapes. So, we may have to go with another CQRS-framework depending on the timing of your .NET-Core decisions. Best regards!

**Comment by cdmdotnet** [comment]
At this point the roadmap for .net core 2.0 does not provide access to enough of the thread management that the base framework does. Microsoft is aiming for more parity with .net core 3 however I expect by .net core version 4 enough of the original low level framework thread management will exist in .net core enabling our project to port without an unreasonable level of effort.
