### ISSUE TITLE
Yes, but why "RSN"?

### ISSUE THREAD

**Issue by corfor** [Chinchilla-Software-Com/CQRS#139]
What does the abbreviation itself mean? Why these three letters? 

Please update doc: 
https://github.com/Chinchilla-Software-Com/CQRS/wiki/Rsn

**Comment by cdmdotnet** [comment]
I can't remember why it was picked, but it won the vote within the team. Something about it being used in a previous project.

I can't find anything specific to indicate what, if any, abbreviation is meant by the 3 letters. It is what it is.
