### ISSUE TITLE
VS solution file is very old. 

### ISSUE THREAD

**Issue by robsiera** [Chinchilla-Software-Com/CQRS#146]
Isn't there a newer version of the sln file available?
Latest sln file is for Visual Studio 2012.

**Comment by cdmdotnet** [comment]
We currently develop using VS 2015. If you are referring to the name of the sln file... that was purely a naming choice several years ago as some components are VS 2010 compatible. It was at that point an easy way for the team to identify minimum compatibility.

Feel free to use newer version of VS if you want.

**Comment by robsiera** [comment]
the file cqrs-2012.sln is a VS2013 file, not VS2015. I tried to migrate it to VS2017 but that was not 100% successful.  I managed to compile most of the projects. I'm still having some errors regarding some of the vsix projects, but I guess those won't be compatible with VS2017.

**Comment by cdmdotnet** [comment]
I stand corrected. We use VS2013 not VS2015 for this project. As for compilation... not all code for the VSIX components are public. That part of the project is a paid for component by some of our clients. That is why those projects won't compile.
