### ISSUE TITLE
Race condition when applying Serivce Bus subscription filters

### ISSUE THREAD

**Issue by DarkDaskin** [Chinchilla-Software-Com/CQRS#147]
https://github.com/Chinchilla-Software-Com/CQRS/blob/3d79e238e7621596a9865e5192147009085e18a7/Framework/Azure/Cqrs.Azure.ServiceBus/AzureEventBusReceiver.cs#L106-L115

This core is run twice - once for public and private topics respectively. Due to a race condition sometimes only one topic gets its subscription filter applied.

**Comment by cdmdotnet** [comment]
Hi @DarkDaskin 

This issue was identified several months ago and patched in commit 008fabbcabb41d45fa309bbe51e6addac1fa88dc as part of #141 

We suggest you update to the later branch, or review the commits as part of #141 to patch any forks you may have.
