### ISSUE TITLE
.Net6 Support

### ISSUE THREAD

**Issue by Zer010** [Chinchilla-Software-Com/CQRS#157]
Since the next LTS is .NET 6 and this is based on the full framework it should be brought up to standard or marked as unmaintained.

**Comment by cdmdotnet** [comment]
Much of the project is dual compiled... both for .NET CORE and .NET for legacy projects.

I don't see why that would mark this project unmaintainable or require any further work than what is already in our roadmap to bring it "up to standard" as you put it.

Essentially, the vast majority of this project is already .netstandard 2.0 compliant and thus is .NET CORE 2.1 -> 6.0 compatible. So no, we won't be marking this project as unmaintained.
