### ISSUE TITLE
CorrelationIdHelper uninitialized when using from other thread

### ISSUE THREAD

**Issue by magol** [Chinchilla-Software-Com/CQRS#6]
When I try to send a command or publish an event from a separate thread, I get a `NullReferenceException` in InProcessBus when it try to use `CorrelationIdHelper.GetCorrelationId()`. 

The reason is that `ICorrelationIdHelper.SetCorrelationId` is only used in the main thread, and when it use `ICorrelationIdHelper.GetCorrelationId()`from a separate thread, `CallContext.GetData("CorrelationIdValue")` returns `null`.

**Comment by cdmdotnet** [comment]
Can you explain a little further your situation? Is this a web based project or something non-web based. There are specific approaches to each which ultimately follow the same theory, but are implemented differently.

**Comment by magol** [comment]
Hi
It's a WPF application
When I send an command from the ViewModel, it's no problem. But in some situations, I send commands from a thread that are running separate from the main thread. 
I'm new

**Comment by cdmdotnet** [comment]
The purpose of the `CorrelationId` is to provide an id that is assigned to all commands and events triggered by the same action. So if a user clicks a button and you raise several commands etc, then you want to be able to group them all together for analysis and debugging.

In most cases the code will take care of passing this value around, but if you are manually creating your own threads, then you will need to pass that value into your created threads and set it by calling the `ICorrelationIdHelper.SetCorrelationId` method as the first step inside your new thread.

If you need further help, provide some sample code please.
