### ISSUE TITLE
The Azure document db package not able to build the aggregate root (fetch events)

### ISSUE THREAD

**Issue by aleenabhat12** [Chinchilla-Software-Com/CQRS#7]
Issue with the change in https://github.com/Chinchilla-Software-Com/CQRS/commit/e25ca98bb161a83951953c8f0b78fb313f6ab8ac
line 52
string collectionName = string.Format("{0}::{1}", AzureDocumentDbEventStoreConnectionStringFactory.GetEventStoreConnectionCollectionName(), aggregateRootType.FullName);

was changed to:
string collectionName = string.Format("{0}", AzureDocumentDbEventStoreConnectionStringFactory.GetEventStoreConnectionCollectionName());

where as in PersitEvent method the methods are saved to the collection with the name in format as mentioned in the first line of code.

**Comment by cdmdotnet** [comment]
I'll review the bug fix in the next day or two.

Thanks heaps for your contribution. It is appreciated.

**Comment by cdmdotnet** [comment]
You're looking at an old branch of code there. The master branch already has a fix. This check-in generated build-1.601.899-170 and we're not at build-1.601.1129-367.

Check the latest code and get back to me.

**Comment by aleenabhat12** [comment]
I have created fix with the updated code.

**Comment by cdmdotnet** [comment]
I see what you mean. As mentioned on your pull request. Once all instances are corrected I'll merge your pull request.

**Comment by cdmdotnet** [comment]
Have a look at commit e2bc7cf1c3a848bac0282482930b4d571c10a4d5
this has an explaination on the approach needed when dealing with Azure DocumentDB due to their pricing structure. You did pick out a bug, just from the wrong end.

Have a look at that commit and let us know if it doesn't fix your issue.
