### ISSUE TITLE
Version check issue

### ISSUE THREAD

**Issue by aleenabhat12** [Chinchilla-Software-Com/CQRS#9]
While checking the expected version, condition x.Version >= fromVersion is incorrect and should be x.Version > fromVersion

This is causing the valid version numbers to fail. This condition is correct for other event sources but wrong for AzureDocumentDB.

https://github.com/Chinchilla-Software-Com/CQRS/blob/master/Framework/Azure/Cqrs.Azure.DocumentDb/Events/AzureDocumentDbEventStore.cs
Line 63

**Comment by cdmdotnet** [comment]
Code corrected. Thanks heaps for pointing this out. You've been credited with fix.
